### ISSUE TITLE
Update of file and data

### ISSUE THREAD

**Issue by Ceciluni** [C2DH/statec-exhibit#80]
Please update this file with the following data
Source: Bernhoeft Charles 1899, Photothèque de la Ville de Luxembourg

Replacing 1899-img332athenee.jpg 
source industrie.lu 
Line 80 of the Google Spreadsheet

**Comment by danieleguido** [comment]
@Ceciluni is this ok? 
![Screenshot 2022-06-24 at 16 55 57](https://user-images.githubusercontent.com/1181642/175561831-857fb2b8-9354-47dc-b17b-c68ba9ee8e94.png)

**Comment by Ceciluni** [comment]
Yes, this is perfect, thank you
